# Generated by Django 3.2.11 on 2022-02-07 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billogram', '0002_auto_20220207_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code_string',
            field=models.TextField(default=uuid.UUID('682cec73-d2aa-4fcb-817a-8870798b15cb')),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percent',
            field=models.IntegerField(default=10),
        ),
    ]
